name: pkgi-ps3-nopaystation release

on:
    push:
        branches:
          - main
    # On csv changes
        paths:
          - output/**
    # Allows you to run this workflow manually from the Actions tab
    workflow_dispatch:

jobs:
    releaser:
        runs-on: ubuntu-latest
        steps:
            - name: 🛎️ Checkout
              uses: actions/checkout@v4
            - name: 📅 Get current date
              id: date
              run: echo "NOW=$(date +'%d-%m-%Y')" >> $GITHUB_OUTPUT
            - uses: ncipollo/release-action@v1.13.0
              name: 🤖 Create release on Github
              with:
                artifacts: "dbformat.txt,output/*.csv"
                allowUpdates: "true"
                replacesArtifacts: "true"
                tag: "nopaystation_${{ steps.date.outputs.NOW }}"
                body: "NoPayStation - release ${{ steps.date.outputs.NOW }}"
                name: "pkgi-ps3-nopaystation ${{ steps.date.outputs.NOW }}"